lib/genio_test_web/router.ex
defmodule GenioTestWeb.Router do
  use GenioTestWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GenioTestWeb do
    pipe_through :browser

    get "/", WizardController, :new
    resources "/quotes", WizardController, only: [:new, :create, :update, :edit, :show] 
  end

  # Other scopes may use custom stacks.
  # scope "/api", GenioTestWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GenioTestWeb.Telemetry
    end
  end
end

lib/genio_test_web/controllers/wizard_controller.ex
defmodule GenioTestWeb.WizardController do
  alias GenioTest.Quote.Quoting
  alias GenioTest.Quote.Quote
  alias GenioTest.Repo
  alias QuoteWizard

  @finish_step :summary

  use GenioTestWeb, :controller

  def new(conn, _params) do
    changeset = Quoting.changeset(%Quoting{})
    render(conn, "quoting.html", changeset: changeset)
  end

  def create(conn, %{"quoting" => quoting_params}) do
    case QuoteWizard.new(quoting_params) do
      {:ok, quote} -> 
        redirect(conn, to: "/quotes/#{quote.token}/edit")
      {:error, changeset} ->
        render(conn, "quoting.html", changeset: changeset)
    end
  end

  def update(conn, params) do
    quote = Repo.get_by(Quote, token: params["id"])
    case QuoteWizard.update(quote, params) do
      {:ok, quote} -> 
        case quote.step == @finish_step do
          :true -> redirect(conn, to: "/quotes/#{quote.token}")
          :false -> redirect(conn, to: "/quotes/#{quote.token}/edit")
        end
      {:ok, changeset, params} -> 
        render(conn, get_step_template(params), params: params, changeset: changeset)
      {:error, changeset, params} -> 
        render(conn, get_step_template(params), params: params, changeset: changeset)
    end
  end

  def edit(conn, params) do
    case QuoteWizard.current(params["id"]) do
      {:ok, quote, changeset} -> 
        render(conn, get_step_template(quote), params: quote, changeset: changeset)
      {:error, _message} -> 
        redirect(conn, to: "/")
    end
  end

  def show(conn, %{"id" => id}) do
    with quote <- Repo.get_by(Quote, token: id),
         true <- quote != nil,
         true <- quote.step == @finish_step do
        render(conn, "summary.html", params: quote)
    else
      _ -> redirect(conn, to: "/quotes/#{id}/edit")
    end
  end

  defp get_step_template(quote) do
    "#{to_string(quote.step)}.html"
  end
end

lib/genio_test_web/views/wizard_view.ex
defmodule GenioTestWeb.WizardView do
  use GenioTestWeb, :view

  #def render("wizard.html", assigns) do
    #template_name = assigns.changeset.data.__struct__
                    #|> to_string()
                    #|> String.replace("Elixir.GenioTest.Quote.", "")
                    #|> String.downcase()

    #template = EEx.eval_file("lib/genio_test_web/templates/wizard/quoting.html.eex", assigns: assigns)
    #require IEx;IEx.pry

     ##Map.replace!(params, :view_template, "#{template_name}.html")
     ##render(params.conn, GenioTestWeb.WizardView, "#{template_name}.html", changeset: params.changeset)
    #~E(<script src="file.js"></script>)
  #end
end

lib/genio_test_web/templates/wizard/address.html.eex
<h1>Address</h1>

<%= form_for @changeset, "/quotes/#{@params.token}", [method: "patch"], fn f -> %>
  <label>
    street: <%= text_input f, :street %>
  </label>
  <label>
    external_number: <%= text_input f, :external_number %>
  </label>
  <label>
    external_number: <%= text_input f, :country %>
  </label>
  <br>
  <%= submit "submit" %>
<% end %>

lib/genio_test_web/templates/wizard/customer.html.eex
<h1>Customer</h1>

<%= form_for @changeset, "/quotes/#{@params.token}", [method: "patch"], fn f -> %>
  <label>
    first_name: <%= text_input f, :first_name %>
  </label>
  <label>
    last_name: <%= text_input f, :last_name %>
  </label>
  <label>
    rfc: <%= text_input f, :rfc %>
  </label>
  <label>
    gender: <%= text_input f, :gender %>
  </label>
  <%= submit "Submit" %>
<% end %>

lib/genio_test_web/templates/wizard/customer_policy.html.eex
<h1>Datos del vehiculo</h1>

<%= case @params.quote.ensurer_quote do %>
  <% "aba" -> %>
  <%= render(GenioTestWeb.OptionsQuoteView, "aba.html", Map.put(assigns, :changeset, @changeset) ) %>
  <% _ -> %>
  <%= render(GenioTestWeb.OptionsQuoteView, "generic.html", Map.put(assigns, :changeset, @changeset)) %>
<% end %>

lib/genio_test_web/templates/wizard/customer_vehicle.html.eex
<h1>Datos de tu vehiculo</h1>

<%= form_for @changeset, "/quotes/#{@params.quote.token}", fn f -> %>
  <label>
    serie: <%= text_input f, :serie %>
  </label>
  <label>
    motor: <%= text_input f, :motor %>
  </label>
  <br>
  <%= submit "submit" %>
<% end %>

<%= form_for @conn,"/quote/#{@params.quote.token}", fn f -> %>
  <%= hidden_input f, :go_back, value: "true" %>
  <%= submit "Atras", class: "btn btn-danger" %>
<% end %>

lib/genio_test_web/templates/wizard/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <label>
    vehicle: <%= text_input f, :vehicle_quote %>
  </label>
  <label>
    age: <%= text_input f, :age %>
  </label>
  <label>
    name: <%= text_input f, :name %>
  </label>
  <label>
    gender: <%= text_input f, :gender %>
  </label>
  <label>
    zip_code: <%= text_input f, :zip_code %>
  </label>
  <label>
    email: <%= text_input f, :email %>
  </label>
  <label>
    phone: <%= text_input f, :phone %>
  </label>
  <%= submit "Submit" %>
<% end %>

lib/genio_test_web/templates/wizard/payment_method.html.eex
<h1>Paymen Method</h1>

<%= form_for @changeset, "/quotes/#{@params.token}", [method: "patch"], fn f -> %>
  <label>
    method: <%= select(f, :method, ["card": "card", "cash": "cash"]) %>
  </label>
  <label>
    periodicity: <%= select(f, :periodicity, ["biannual": "biannual", "quarterly": "quarterly", "monthly": "monthly"]) %>
  </label>
  <br>
  <%= submit "submit" %>
<% end %>

<%= form_for @conn,"/quotes/#{@params.token}", [method: "patch"], fn f -> %>
  <%= hidden_input f, :go_back, value: "true" %>
  <%= submit "Atras", class: "btn btn-danger" %>
<% end %>

lib/genio_test_web/templates/wizard/quoting.html.eex
<h1>Nueva cotizacion</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.wizard_path(@conn, :create)) %>

lib/genio_test_web/templates/wizard/summary.html.eex
<h1>Summary</h1>

<h2>Customer</h2>
<p>name: <%= @params.customer.first_name %></p>
<p>last_name: <%= @params.customer.last_name %></p>
<p>rfc: <%= @params.customer.rfc %></p>
<p>email: <%= @params.customer.rfc %></p>

<h2>Vehicle</h2>
<p>make: <%= @params.vehicle.make %></p>
<p>model: <%= @params.vehicle.year_model %></p>
<p>version: <%= @params.vehicle.version %></p>

<h2>Address</h2>
<p>street: <%= @params.address.street %></p>
<p>external_number: <%= @params.address.external_number %></p>
<p>country: <%= @params.address.country %></p>

<h2>Payment method</h2>
<p>method: <%= @params.payment_method.method %></p>
<p>periodicity: <%= @params.payment_method.periodicity %></p>

lib/genio_test_web/templates/wizard/vehicle.html.eex
<h1>vehicle</h1>

<%= form_for @changeset, "/quotes/#{@params.token}", [method: "patch"], fn f -> %>
  <label>
    Select make <%= select(f, :make, ["Make1": "make1", "Make2": "make2", "Make3": "make3"], prompt: "Selecciona una marca") %>
  </label>
  <label>
    Select model <%= select(f, :year_model, 2021..1990, prompt: "Selecciona un modelo") %>
  </label>
  <label>
    Select model <%= select(f, :version, ["np300": "np300", "cdl": "cdl",], prompt: "Selecciona una version") %>
  </label>
  <%= submit "Submit" %>
<% end %>